# Generated by Django 4.0.4 on 2022-05-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
